name: 'A Love Story Wedding & Event Planning'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a286c0'
    - '#d6cae0'
    - '#40374c'
    - '#756388'
    - '#b6aac0'
  brandStrength: 1
  lightness: 0.7299136554356664
  saturation: 0.8118156099226326
  rhythmicContrast: 0.4689454382751137
purpose: []
